[window]
padding = {x = 8, y = 8}
title = "cocotreb@tpt14g5:~"
dynamic_title = true
opacity = 1

[font]
normal = {family = "JetBrainsMonoNerdFont"}
size = 13

[colors.primary]
background = '#272e33'
foreground = '#d3c6aa'

[colors.normal]
black   = '#414b50'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

# [colors.bright]
# black   = '#475258'
# red     = '#e67e80'
# green   = '#a7c080'
# yellow  = '#dbbc7f'
# blue    = '#7fbbb3'
# magenta = '#d699b6'
# cyan    = '#83c092'
# white   = '#d3c6aa'

